### Import Library and data

In [10]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "../data/processed/tourism_arrivals_clean.csv"
)

### describe

In [11]:
df["Tourist_Arrivals"].describe()

count    18720.000000
mean       618.213622
std       2902.100493
min          0.000000
25%          0.000000
50%          6.000000
75%        116.000000
max      56715.000000
Name: Tourist_Arrivals, dtype: float64

In [12]:
mean_arrivals = df["Tourist_Arrivals"].mean()

print("Mean:", mean_arrivals)

Mean: 618.2136217948718

In [13]:
median_arrivals = df["Tourist_Arrivals"].median()

print("Median:", median_arrivals)

Median: 6.0

In [14]:
std_arrivals = df["Tourist_Arrivals"].std()

print("Standard Deviation:", std_arrivals)

Standard Deviation: 2902.100492816507

In [15]:
print("Minimum:", df["Tourist_Arrivals"].min())
print("Maximum:", df["Tourist_Arrivals"].max())

Minimum: 0.0
Maximum: 56715.0

### Country statistics

In [16]:
country_stats = (
    df.groupby("Country")["Tourist_Arrivals"]
    .agg(
        Total="sum",
        Average="mean",
        Median="median",
        Maximum="max",
        Minimum="min"
    )
    .sort_values("Total", ascending=False)
)

country_stats.head(20)

,Total,Average,Median,Maximum,Minimum
Country,,,,,
India,1374333.0,28631.937500,30045.0,56715.0,5340.0
Russian Federation,677270.0,14109.791667,10498.0,35268.0,1426.0
United Kingdom,605891.0,12622.729167,11289.5,25528.0,2872.0
UNITED KINGDOM,525053.0,10938.604167,8419.0,30366.0,0.0
INDIA,500627.0,13906.305556,8467.0,48442.0,0.0
Germany,442131.0,9211.062500,8366.0,18324.0,2149.0
"INDIA, REPUBLIC OF",424887.0,35407.250000,32942.5,45797.0,29860.0
GERMANY,338736.0,7057.000000,6135.5,24423.0,0.0
China,337220.0,7025.416667,8556.0,16709.0,226.0
Australia,297420.0,6196.250000,6230.0,14820.0,1660.0
France,289549.0,6032.270833,5489.5,15469.0,1076.0
"CHINA, PEOPLE'S REPUBLIC OF",265965.0,22163.750000,20012.0,35929.0,17103.0
AUSTRALIA,228306.0,4756.375000,4641.5,14961.0,0.0
RUSSIAN FEDERATION,217337.0,4527.854167,1282.0,20948.0,0.0
CHINA,196427.0,5456.305556,230.0,28039.0,0.0
United States,194079.0,4043.312500,3873.0,8524.0,991.0
Canada,159134.0,3315.291667,3318.5,5737.0,1552.0
Netherlands,155323.0,3235.895833,2547.5,15556.0,423.0
Maldives,140595.0,2929.062500,2811.5,8040.0,567.0
Poland,127295.0,2651.979167,2115.0,8519.0,203.0

### Year statistics

In [18]:
year_stats = (
    df.groupby("Year")["Tourist_Arrivals"]
    .agg([
        "sum",
        "mean",
        "median",
        "std",
        "min",
        "max"
    ])
)

year_stats

            sum         mean  median          std  min      max
Year
2018  2333796.0   987.223350    19.0  3767.398605  0.0  45797.0
2019  1913702.0   822.036942    16.0  3271.288344  0.0  48442.0
2020   507699.0   225.043883     0.0  1773.249648  0.0  41448.0
2021   194495.0    75.737928     0.0   701.492511  0.0  23566.0
2022   719978.0   319.139184     7.0  1367.625512  0.0  23216.0
2023  1487303.0   652.325877    16.0  2699.408521  0.0  43973.0
2024  2053465.0   886.642919    17.0  3509.537744  0.0  52881.0
2025  2362521.0  1004.473214    19.0  4087.366504  0.0  56715.0

In [19]:
year_stats.to_csv(
    "../data/processed/yearly_descriptive_statistics.csv"
)

country_stats.to_csv(
    "../data/processed/country_descriptive_statistics.csv"
)